export const languageData = {
    en: {
        "do-it": "Do-it",
        "your-name": "Your Name?",
        "filters-tasks": "Filters Tasks",
        "all": "All",
        "active": "Active",
        "completed": "Completed",
        "tasks": "Tasks",
        "settings": "Settings",
        "focus-for-today": "Focus for Today",
        "stay-productive": "Stay Productive",
        "theme": "Theme",
        "current-theme": "Current Theme: Light",
        "edit-profile": "Edit Profile",
        "your-name": "Your Name:",
        "save": "Save",
        "reset-tasks": "Reset Tasks",
        "clear-tasks": "Clear all tasks from your todo list.",
        "reset-tasks-btn": "Reset Tasks",
    },
    ru: {
        "do-it": "Сделай это",
        "your-name": "Твое имя?",
        "filters-tasks": "Фильтры задач",
        "all": "Все",
        "active": "Активные",
        "completed": "Завершенные",
        "tasks": "Задачи",
        "settings": "Настройки",
        "focus-for-today": "Фокус на сегодня",
        "stay-productive": "Оставайтесь продуктивными",
        "theme": "Тема",
        "current-theme": "Текущая тема: Светлая",
        "edit-profile": "Редактировать профиль",
        "your-name": "Ваше имя:",
        "save": "Сохранить",
        "reset-tasks": "Сбросить задачи",
        "clear-tasks": "Очистить все задачи из списка.",
        "reset-tasks-btn": "Сбросить задачи",
    }
};
